### ISSUE TITLE
[FIXED] Doesn't work correctly with N64 games on RetroArch

### ISSUE THREAD

**Issue by Skyyblaze** [blurbusters/crt-beam-simulator#5]
I've tried the CRT Beam Simulator Shader so far with SNES, PSX and Dreamcast games and it all works fantastic there however I can't get it to work properly with N64 cores. It doesn't matter if I use ParaLLEl or Mupen64 Next Plus, both with the Angrylion GPU plugin. Having D3D12 as the video backend results in a black screen once loading the CRT Beam Simulation shader but audio and inputs are still being processed.

Switching the backend to Vulkan allows for an image with the shader however it is flickering intensely and there are "ghost frames". Is there anything specific about N64 games and their cores that doesn't allow the shader to work properly?

I'm using the latest RetroArch nightly and the latest cores.

**Comment by mdrejhon** [comment]
Hello!

Welcome! But you submitted to the wrong bug repository.
Please submit it to Retroarch: https://github.com/libretro/RetroArch/issues

You submitted the bug to the global central repository of the shader used by multiple customers (including non-Retroarch customers where the N64 actually works privately in the laboratory), so this is a Retroarch-specific bug.  I don't know why Retroarch has a bug with the CRT simulator on N64 cores.

**Comment by Skyyblaze** [comment]
Hello @mdrejhon!

It makes perfect sense that I should have rather posted this on the RetroArch Planet and I was already there in their orbit and drafting a contact message but then something happened that flabbergasted me. I was running through everything again to give Planet RetroArch sensor logs of the issue but now it doesn't happen again anymore o.o

I restarted RA a couple of times and I didn't change any settings compared to yesterday though the CRT Beam Simulator UFO Module is now working perfectly as expected with N64 content. So I am genuinely not sure what caused the issue in the first place nor why it now does work fine with seemingly no change.

I'll definitely hail Planet RetroArch should I manage to reproduce it but for now sorry to have bothered you and thanks for all your hard work! You make Retro content and general gaming much more enjoyable with this :)

**Comment by mdrejhon** [comment]
Glad this is fixed!

Retroarch needs to be restarted after you change major settings sometimes, since the CRT simulator is incompatible until you're successfully running in subframe-processing mode.   

You need at least 2 native refresh cycles per simulated refresh cycle (CRT), and preferably 3 or 4, so it mandatorily requires subframe-processing mode which sometimes doesn't always turn on in Retroarch.

**Comment by mdrejhon** [comment]
RetorArch setting quirk behavior fixed

**Comment by Skyyblaze** [comment]
> Glad this is fixed!
> 
> Retroarch needs to be restarted after you change major settings sometimes, since the CRT simulator is incompatible until you're successfully running in subframe-processing mode. Then it will remember/save that setting properly. RetroArch can get slightly confused if you turn on/off a lot of settings including CRT and subframe modes, and sometimes a combination stops working.
> 
> On the other hand, if it's a clean start of Retroarch in true subframe mode right out of gate at startup -- and the CRT simulator does not work -- it may be a settings-save issue (Retroarch "forgetting" your settings). If so, report that.
> 
> At the end of the day: You need at least 2 native refresh cycles per simulated refresh cycle (CRT), and preferably 3 or 4, so it mandatorily requires subframe-processing mode which might not have properly turned on in Retroarch if you were toggling on/off so many settings at once.

I think that might have been exactly it! I had to mess with per-core configs because normally the N64 cores wanted to switch the GPU backend to glcore so maybe when I initially forced them onto Vulkan/D3D12 after setting them to Angrylion the Shader Subframes didn't start correctly until I actually saved the per-core override and then did a full restart the next day.

And yeah _I know more than 120hz would be even better but it's still a great experience like that already for my setup. I hope that RetroArch eventually gets full arbitrary subframe support so I can leverage my full 160hz at least.
